import { ArrowUpRight, BriefcaseBusiness, Check, Code2 } from "lucide-react";
import { Link } from "@/i18n/navigation";
import { capabilities, copy } from "@/lib/content";

type Props = { params: Promise<{ locale: string }> };

export default async function AboutPage({ params }: Props) {
  const { locale } = await params;
  const en = locale === "en";
  const principles = en ? ["Make the complicated feel obvious.", "Ship something useful before polishing the story.", "Leave systems easier to change than you found them.", "Keep learning visible, but keep the work real."] : ["Làm cho điều phức tạp trở nên dễ hiểu.", "Đưa thứ có ích vào tay người dùng trước khi kể câu chuyện thật đẹp.", "Để hệ thống dễ thay đổi hơn lúc mình bắt đầu.", "Cho thấy quá trình học, nhưng luôn bắt đầu từ việc thật."];
  return <main className="container-page py-14 sm:py-20"><div className="grid gap-8 lg:grid-cols-[1.1fr_.9fr] lg:items-end"><div><span className="section-kicker">about / the builder</span><h1 className="mt-5 max-w-4xl text-5xl font-extrabold leading-[.95] tracking-tight sm:text-7xl">{en ? <>Hi, I&apos;m <span className="text-orange">Annam.</span></> : <>Chào, mình là <span className="text-orange">Annam.</span></>}</h1><p className="mt-7 max-w-2xl text-xl font-medium leading-relaxed">{en ? "A fourth-year IT student and full-stack developer from Vietnam. I like useful software, clear interfaces, and the part where an idea becomes something people can actually use." : "Sinh viên năm 4 ngành Công nghệ thông tin và full-stack developer tại Việt Nam. Mình thích phần mềm có ích, giao diện rõ ràng và khoảnh khắc một ý tưởng trở thành thứ người khác thật sự dùng được."}</p></div><div className="neo-card bg-lilac p-6"><p className="mono-label">{en ? "Short version" : "Bản ngắn gọn"}</p><p className="mt-5 text-2xl font-extrabold leading-tight">{en ? "I care about the distance between a messy problem and a calm product." : "Mình quan tâm đến khoảng cách giữa một vấn đề rối và một sản phẩm bình tĩnh."}</p></div></div><div className="mt-16 grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><section className="neo-card bg-orange p-6 sm:p-8"><span className="section-kicker">01 / principles</span><ul className="mt-8 grid gap-5">{principles.map((item) => <li key={item} className="flex gap-3 text-lg font-extrabold leading-snug"><Check className="mt-0.5 shrink-0" size={22} />{item}</li>)}</ul></section><section><span className="section-kicker">02 / capabilities</span><h2 className="mt-4 text-3xl font-extrabold sm:text-4xl">{en ? "I work across product and engineering." : "Mình làm ở giao điểm giữa sản phẩm và kỹ thuật."}</h2><div className="mt-7 grid gap-4 sm:grid-cols-2">{capabilities.map((item, index) => <div key={item.en} className="neo-card-sm bg-cream p-5"><span className="mono-label">0{index + 1}</span><p className="mt-8 text-xl font-extrabold">{copy(item, locale)}</p></div>)}</div></section></div><section className="mt-16 border-y-[3px] border-ink py-12"><div className="grid gap-8 sm:grid-cols-[.8fr_1.2fr]"><div><span className="section-kicker">03 / elsewhere</span><h2 className="mt-4 text-3xl font-extrabold">{en ? "Keep in touch" : "Kết nối với mình"}</h2></div><div className="flex flex-wrap items-start gap-3"><a className="neo-button neo-button-plain" href="https://github.com/Miikey24s" target="_blank" rel="noreferrer"><Code2 size={18} /> GitHub <ArrowUpRight size={16} /></a><a className="neo-button neo-button-lilac" href="https://www.linkedin.com" target="_blank" rel="noreferrer"><BriefcaseBusiness size={18} /> LinkedIn <ArrowUpRight size={16} /></a><Link className="neo-button neo-button-orange" href="/contact">{en ? "Contact" : "Liên hệ"} <ArrowUpRight size={18} /></Link></div></div></section></main>;
}
