import { ArrowUpRight, CalendarDays, Circle } from "lucide-react";
import { Link } from "@/i18n/navigation";

type Props = { params: Promise<{ locale: string }> };

export default async function NowPage({ params }: Props) {
  const { locale } = await params;
  const en = locale === "en";
  const items = en
    ? ["Turning this portfolio into a clearer record of real work and experiments.", "Collecting safe screenshots and short stories from real projects.", "Keeping .NET, Blazor, Unity, and AI experiments in the same learning loop."]
    : ["Biến portfolio này thành nơi lưu lại dự án thật và các experiment đang mở.", "Chọn lọc ảnh và câu chuyện có thể công khai từ dự án thật.", "Tiếp tục .NET, Blazor, Unity và AI experiments trong cùng một vòng học hỏi."];

  return <main className="container-page py-14 sm:py-20"><div className="grid gap-8 lg:grid-cols-[1fr_.8fr] lg:items-end"><div><span className="section-kicker">{en ? "now / current" : "now / hiện tại"}</span><h1 className="mt-5 max-w-4xl text-5xl font-extrabold leading-[.92] tracking-tight sm:text-7xl">{en ? <>Current <span className="text-orange">focus.</span></> : <>Hiện <span className="text-orange">tại.</span></>}</h1><p className="mt-7 max-w-2xl text-xl font-medium leading-relaxed">{en ? "A short, honest snapshot of what I am prioritizing, testing, and learning next." : "Một ghi nhận ngắn và thật về những việc mình đang ưu tiên, thử nghiệm và học tiếp."}</p></div><div className="neo-card bg-yellow p-6"><div className="flex items-center justify-between"><span className="mono-label">{en ? "last updated" : "cập nhật lần cuối"}</span><CalendarDays size={20} /></div><p className="mt-7 text-3xl font-extrabold">13 / 08 / 2026</p><p className="mt-2 font-medium">{en ? "Asia / Saigon" : "Múi giờ Việt Nam"}</p></div></div><div className="mt-14 grid gap-5 lg:grid-cols-[.85fr_1.15fr]"><div className="neo-card bg-lilac p-6 sm:p-8"><span className="section-kicker">{en ? "open route" : "open route"}</span><div className="mt-8 grid gap-6">{items.map((item, index) => <div key={item} className="flex gap-4"><span className="flex h-9 w-9 shrink-0 items-center justify-center border-[3px] border-ink bg-cream font-extrabold">0{index + 1}</span><p className="pt-1 text-lg font-extrabold leading-snug">{item}</p></div>)}</div></div><div className="neo-card grid-paper bg-cream p-6 sm:p-8"><span className="section-kicker">{en ? "working definition" : "tiêu chí đang dùng"}</span><h2 className="mt-7 text-3xl font-extrabold">{en ? "A project can start small." : "Một dự án có thể bắt đầu nhỏ."}</h2><p className="mt-5 text-lg leading-relaxed">{en ? "What matters is a clear state, honest evidence, and a useful next step. The page can evolve as those things become available." : "Điều quan trọng là trạng thái rõ ràng, bằng chứng trung thực và bước tiếp theo hữu ích. Website sẽ thay đổi khi những điều đó xuất hiện."}</p><Link href="/blog" className="mt-8 inline-flex items-center gap-2 font-extrabold underline decoration-2 underline-offset-4">{en ? "Read the notes" : "Đọc các ghi chú"} <ArrowUpRight size={18} /></Link></div></div><div className="mt-14 border-t-[3px] border-ink pt-8"><p className="mono-label">{en ? "Next small move" : "Bước tiếp theo"}</p><p className="mt-4 flex items-center gap-3 text-2xl font-extrabold"><Circle size={16} fill="currentColor" />{en ? "Add one project story with safe evidence." : "Thêm một câu chuyện dự án có bằng chứng an toàn."}</p></div></main>;
}
