import { ArrowUpRight, CalendarDays, Circle } from "lucide-react";
import { Link } from "@/i18n/navigation";

type Props = { params: Promise<{ locale: string }> };

export default async function NowPage({ params }: Props) {
  const { locale } = await params;
  const en = locale === "en";
  const items = en ? ["Turning this portfolio into a clearer work archive.", "Collecting safe screenshots and short stories from real projects.", "Keeping .NET, Blazor, Unity and AI experiments in the same learning loop."] : ["Biến portfolio này thành một work archive rõ ràng hơn.", "Thu thập screenshot an toàn và câu chuyện ngắn từ các project thật.", "Giữ .NET, Blazor, Unity và AI experiments trong cùng một vòng học hỏi."];
  return <main className="container-page py-14 sm:py-20"><div className="grid gap-8 lg:grid-cols-[1fr_.8fr] lg:items-end"><div><span className="section-kicker">now / current state</span><h1 className="mt-5 max-w-4xl text-5xl font-extrabold leading-[.92] tracking-tight sm:text-7xl">{en ? <>Still <span className="text-orange">building.</span></> : <>Vẫn đang <span className="text-orange">xây.</span></>}</h1><p className="mt-7 max-w-2xl text-xl font-medium leading-relaxed">{en ? "A small, honest snapshot of what has my attention right now. This page changes before the rest of the site does." : "Một snapshot nhỏ và thật về điều đang chiếm sự tập trung của mình. Trang này được cập nhật trước khi phần còn lại của site thay đổi."}</p></div><div className="neo-card bg-yellow p-6"><div className="flex items-center justify-between"><span className="mono-label">last updated</span><CalendarDays size={20} /></div><p className="mt-7 text-3xl font-extrabold">13 / 08 / 2026</p><p className="mt-2 font-medium">{en ? "Asia / Saigon" : "Múi giờ Việt Nam"}</p></div></div><div className="mt-14 grid gap-5 lg:grid-cols-[.85fr_1.15fr]"><div className="neo-card bg-lilac p-6 sm:p-8"><span className="section-kicker">the current loop</span><div className="mt-8 grid gap-6">{items.map((item, index) => <div key={item} className="flex gap-4"><span className="flex h-9 w-9 shrink-0 items-center justify-center border-[3px] border-ink bg-cream font-extrabold">0{index + 1}</span><p className="pt-1 text-lg font-extrabold leading-snug">{item}</p></div>)}</div></div><div className="neo-card grid-paper bg-cream p-6 sm:p-8"><span className="section-kicker">definition of done</span><h2 className="mt-7 text-3xl font-extrabold">{en ? "A living site does not need to look finished all the time." : "Một site sống không cần lúc nào cũng trông như đã hoàn thành."}</h2><p className="mt-5 text-lg leading-relaxed">{en ? "It needs to stay useful, honest, and easy to update. New projects can start as a small card. Notes can be short. The system should make the next update feel lighter." : "Nó cần hữu ích, chân thật và dễ cập nhật. Project mới có thể bắt đầu bằng một card nhỏ. Note có thể ngắn. Hệ thống phải làm cho lần cập nhật tiếp theo nhẹ hơn."}</p><Link href="/blog" className="mt-8 inline-flex items-center gap-2 font-extrabold underline decoration-2 underline-offset-4">{en ? "Read the notes" : "Đọc các notes"} <ArrowUpRight size={18} /></Link></div></div><div className="mt-14 border-t-[3px] border-ink pt-8"><p className="mono-label">{en ? "Next small move" : "Bước nhỏ tiếp theo"}</p><p className="mt-4 flex items-center gap-3 text-2xl font-extrabold"><Circle size={16} fill="currentColor" />{en ? "Add one real project story, with safe evidence." : "Thêm một câu chuyện project thật, cùng bằng chứng an toàn."}</p></div></main>;
}
