import { ArrowDownRight, ArrowUpRight, Check, Code2, Sparkles } from "lucide-react";
import { Link } from "@/i18n/navigation";
import ProjectCard from "@/components/ui/ProjectCard";
import { capabilities, copy, notes, projects } from "@/lib/content";

type Props = { params: Promise<{ locale: string }> };

export default async function HomePage({ params }: Props) {
  const { locale } = await params;
  const en = locale === "en";
  const featured = projects.filter((project) => project.featured).slice(0, 3);
  const recentNotes = notes.slice(0, 2);
  return <>
    <section className="container-page relative grid gap-8 pb-16 pt-12 sm:pb-24 sm:pt-20 lg:grid-cols-[1.15fr_.85fr] lg:items-end">
      <div className="absolute -right-24 top-20 hidden h-48 w-48 rounded-full border-[3px] border-ink bg-yellow lg:block" aria-hidden="true" />
      <div className="relative z-10"><span className="sticker bg-lilac">{en ? "Available for good work" : "Sẵn sàng cho việc có ý nghĩa"}</span><h1 className="mt-7 max-w-4xl text-[clamp(3.3rem,9vw,7.8rem)] font-extrabold leading-[.88] tracking-[-.075em]">{en ? <>I build <span className="text-orange">useful</span> things.</> : <>Mình xây những thứ <span className="text-orange">có ích.</span></>}</h1><p className="mt-7 max-w-2xl text-lg font-medium leading-relaxed sm:text-xl">{en ? "Full-stack developer and product-minded builder. Systems, dashboards, mobile workflows, and experiments that turn messy work into clearer action." : "Full-stack developer và product-minded builder. Hệ thống, dashboard, mobile workflow và những thử nghiệm biến công việc rối thành hành động rõ ràng hơn."}</p><div className="mt-8 flex flex-wrap gap-4"><Link href="/projects" className="neo-button neo-button-orange">{en ? "See my work" : "Xem dự án"} <ArrowUpRight size={18} /></Link><Link href="/now" className="neo-button neo-button-plain">{en ? "What I am building" : "Mình đang làm gì"} <ArrowDownRight size={18} /></Link></div></div>
      <div className="relative z-10 neo-card grid-paper bg-cream p-5 sm:p-7"><div className="flex items-center justify-between border-b-2 border-ink pb-4"><span className="mono-label">/ current-build.log</span><span className="flex items-center gap-2 text-xs font-bold"><span className="h-3 w-3 rounded-full border-2 border-ink bg-orange" /> online-ish</span></div><div className="py-7"><Code2 size={36} className="mb-6" /><p className="mono-label text-muted">{en ? "Now building" : "Đang xây"}</p><p className="mt-2 text-2xl font-extrabold leading-tight">{en ? "A portfolio that can keep changing." : "Một portfolio có thể tiếp tục thay đổi."}</p><div className="mt-7 grid gap-3 text-sm font-semibold"><p className="flex items-center gap-2"><Check size={17} /> {en ? "Useful systems over empty hype" : "Hệ thống có ích, không chỉ lời hay"}</p><p className="flex items-center gap-2"><Check size={17} /> {en ? "Projects that tell the real story" : "Project kể câu chuyện thật"}</p><p className="flex items-center gap-2"><Check size={17} /> {en ? "Small updates, long-term momentum" : "Cập nhật nhỏ, tiến bộ dài hạn"}</p></div></div><div className="border-t-2 border-ink pt-4 text-xs font-semibold">vi/en · .NET · Blazor · Unity · AI experiments</div></div>
    </section>

    <section className="border-y-[3px] border-ink bg-orange"><div className="container-page flex flex-wrap items-center justify-between gap-4 py-4"><p className="mono-label">{en ? "Selected signal" : "Một vài tín hiệu"}</p><p className="font-extrabold">{en ? "Systems · interfaces · experiments · learning in public" : "Hệ thống · giao diện · thử nghiệm · học trong quá trình làm"}</p><Sparkles size={24} /></div></section>

    <section className="container-page py-20 sm:py-28"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><span className="section-kicker">01 / work</span><h2 className="mt-4 text-4xl font-extrabold tracking-tight sm:text-6xl">{en ? "Selected work" : "Những project chính"}</h2></div><Link href="/projects" className="font-extrabold underline decoration-2 underline-offset-4">{en ? "View all work" : "Xem tất cả dự án"} <ArrowUpRight className="inline" size={17} /></Link></div><div className="mt-10 grid gap-8 lg:grid-cols-3">{featured.map((project) => <ProjectCard key={project.slug} project={project} locale={locale} featured />)}</div></section>

    <section className="border-y-[3px] border-ink bg-lilac"><div className="container-page grid gap-10 py-20 sm:py-24 lg:grid-cols-[.8fr_1.2fr]"><div><span className="section-kicker">02 / capabilities</span><h2 className="mt-4 text-4xl font-extrabold tracking-tight sm:text-6xl">{en ? "What I build" : "Mình xây gì"}</h2><p className="mt-5 max-w-sm text-lg font-medium leading-relaxed">{en ? "Not a list of buzzwords. These are the kinds of outcomes I like to make real." : "Không phải danh sách buzzword. Đây là những đầu ra mình thích biến thành thứ chạy được."}</p></div><div className="grid gap-4 sm:grid-cols-2">{capabilities.map((item, index) => <div key={item.en} className="neo-card-sm bg-cream p-5"><span className="mono-label">0{index + 1}</span><p className="mt-10 text-xl font-extrabold">{copy(item, locale)}</p><span className="mt-5 block h-2 w-16 bg-orange" /></div>)}</div></div></section>

    <section className="container-page grid gap-8 py-20 sm:py-28 lg:grid-cols-[1fr_1.1fr]"><div className="neo-card bg-yellow p-6 sm:p-8"><span className="section-kicker">03 / now</span><h2 className="mt-8 text-4xl font-extrabold leading-tight sm:text-5xl">{en ? "The website is part of the work." : "Website cũng là một phần của quá trình làm."}</h2><p className="mt-5 text-lg font-medium leading-relaxed">{en ? "A living portfolio is a small feedback loop: ship a project, write a note, learn, repeat." : "Một portfolio sống là một vòng lặp nhỏ: đưa project lên, viết một note, học thêm, rồi lặp lại."}</p><Link href="/now" className="neo-button neo-button-plain mt-8">{en ? "Open /now" : "Mở /now"} <ArrowUpRight size={18} /></Link></div><div><div className="flex items-center justify-between"><span className="section-kicker">04 / notes</span><Link href="/blog" className="font-extrabold underline decoration-2 underline-offset-4">{en ? "All notes" : "Tất cả ghi chú"}</Link></div><div className="mt-5 grid gap-4">{recentNotes.map((note) => <Link key={note.slug} href={`/blog/${note.slug}`} className="neo-card-sm group bg-cream p-5 transition-transform hover:-translate-y-1"><div className="flex items-center justify-between gap-4"><span className="mono-label">{copy(note.tag, locale)}</span><span className="text-xs font-bold">{note.readTime} min</span></div><h3 className="mt-6 text-xl font-extrabold">{copy(note.title, locale)}</h3><p className="mt-2 leading-relaxed">{copy(note.excerpt, locale)}</p><span className="mt-5 inline-flex items-center gap-2 font-extrabold">{en ? "Read" : "Đọc"} <ArrowUpRight size={17} className="transition-transform group-hover:translate-x-1 group-hover:-translate-y-1" /></span></Link>)}</div></div></section>

    <section className="container-page pb-20 sm:pb-28"><div className="neo-card grid gap-8 bg-ink p-7 text-paper sm:p-10 lg:grid-cols-[1.1fr_.9fr] lg:items-end"><div><span className="sticker border-paper bg-orange text-ink">05 / contact</span><h2 className="mt-7 max-w-2xl text-4xl font-extrabold leading-tight sm:text-6xl">{en ? "Have a problem worth building around?" : "Bạn có một vấn đề đáng để cùng xây không?"}</h2></div><div><p className="text-lg leading-relaxed text-paper/75">{en ? "Tell me what is messy, what matters, and what a useful outcome looks like." : "Kể mình nghe điều gì đang rối, điều gì quan trọng và một kết quả có ích sẽ trông như thế nào."}</p><Link href="/contact" className="neo-button neo-button-orange mt-7">{en ? "Start a conversation" : "Bắt đầu trao đổi"} <ArrowUpRight size={18} /></Link></div></div></section>
  </>;
}
